### ISSUE TITLE
Fully integrated Fiori App

### ISSUE THREAD

**Issue by saschakiefer** [saschakiefer/generator-openui5#21]
The current app template has a Fiori Style and Interaction Pattern. Nevertheless can't it be integrated in the Fiori infrastructure (i.e. Fiori Launchpad), yet. That should be provided

**Comment by js1972** [comment]
Templates refactoring is in process. All component-based apps will be usable from within the fiori lanuchpad.

**Comment by js1972** [comment]
Any component-based app can be used within FLP assuming a few simple guidelines are followed. For now I recommend that if you want to build a fiori-like app using SAPUI5 instead of OpenUI5 that you scaffold out the app using WebIDE (trial version is fine) the git clone it locally and use the build sub-generator to add Grunt tools to it for local dev.
You're app will then be setup directly for use within the FLP an it will come with Routing configured into the component as well...
